// <autogenerated />
namespace ExceptionExplorer.UI
{
    partial class ExceptionExplorerForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region WindowPositions Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.ToolStripSeparator toolStripMenuItem1;
            System.Windows.Forms.ToolStripSeparator toolStripMenuItem3;
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ExceptionExplorerForm));
            this.menuBar = new System.Windows.Forms.MenuStrip();
            this.mnuFile = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuFileOpen = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuFileRecent = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuFileRecentNone = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator1 = new System.Windows.Forms.ToolStripSeparator();
            this.mnuFileExit = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuView = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuViewReload = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuViewBack = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuViewForward = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripMenuItem2 = new System.Windows.Forms.ToolStripSeparator();
            this.mnuViewShowSourceCode = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator2 = new System.Windows.Forms.ToolStripSeparator();
            this.mnuViewOptions = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuHelp = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuHelpWebsite = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuHelpUpdate = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuHelpLicenceBar = new System.Windows.Forms.ToolStripSeparator();
            this.mnuHelpPurchase = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuHelpActivate = new System.Windows.Forms.ToolStripMenuItem();
            this.toolStripSeparator3 = new System.Windows.Forms.ToolStripSeparator();
            this.mnuHelpAbout = new System.Windows.Forms.ToolStripMenuItem();
            this.mnuUpdate = new System.Windows.Forms.ToolStripMenuItem();
            this.exceptionControl = new ExceptionExplorer.UI.ExceptionControl();
            this.toolBar = new ExceptionExplorer.UI.AutoToolStrip();
            toolStripMenuItem1 = new System.Windows.Forms.ToolStripSeparator();
            toolStripMenuItem3 = new System.Windows.Forms.ToolStripSeparator();
            this.menuBar.SuspendLayout();
            this.SuspendLayout();
            // 
            // toolStripMenuItem1
            // 
            toolStripMenuItem1.Name = "toolStripMenuItem1";
            toolStripMenuItem1.Size = new System.Drawing.Size(133, 6);
            // 
            // toolStripMenuItem3
            // 
            toolStripMenuItem3.Name = "toolStripMenuItem3";
            toolStripMenuItem3.Size = new System.Drawing.Size(170, 6);
            // 
            // menuBar
            // 
            this.menuBar.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuFile,
            this.mnuView,
            this.mnuHelp,
            this.mnuUpdate});
            this.menuBar.Location = new System.Drawing.Point(0, 0);
            this.menuBar.Name = "menuBar";
            this.menuBar.Size = new System.Drawing.Size(753, 24);
            this.menuBar.TabIndex = 5;
            // 
            // mnuFile
            // 
            this.mnuFile.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuFileOpen,
            toolStripMenuItem1,
            this.mnuFileRecent,
            this.toolStripSeparator1,
            this.mnuFileExit});
            this.mnuFile.Name = "mnuFile";
            this.mnuFile.Size = new System.Drawing.Size(37, 20);
            this.mnuFile.Text = "&File";
            // 
            // mnuFileOpen
            // 
            this.mnuFileOpen.Image = global::ExceptionExplorer.Properties.Resources.open;
            this.mnuFileOpen.Name = "mnuFileOpen";
            this.mnuFileOpen.Size = new System.Drawing.Size(136, 22);
            this.mnuFileOpen.Text = "&Open...";
            this.mnuFileOpen.Click += new System.EventHandler(this.mnuFileOpen_Click);
            // 
            // mnuFileRecent
            // 
            this.mnuFileRecent.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuFileRecentNone});
            this.mnuFileRecent.Name = "mnuFileRecent";
            this.mnuFileRecent.Size = new System.Drawing.Size(136, 22);
            this.mnuFileRecent.Text = "&Recent Files";
            // 
            // mnuFileRecentNone
            // 
            this.mnuFileRecentNone.Enabled = false;
            this.mnuFileRecentNone.Name = "mnuFileRecentNone";
            this.mnuFileRecentNone.Size = new System.Drawing.Size(109, 22);
            this.mnuFileRecentNone.Text = "(none)";
            // 
            // toolStripSeparator1
            // 
            this.toolStripSeparator1.Name = "toolStripSeparator1";
            this.toolStripSeparator1.Size = new System.Drawing.Size(133, 6);
            // 
            // mnuFileExit
            // 
            this.mnuFileExit.Name = "mnuFileExit";
            this.mnuFileExit.Size = new System.Drawing.Size(136, 22);
            this.mnuFileExit.Text = "E&xit";
            this.mnuFileExit.Click += new System.EventHandler(this.mnuFileExit_Click);
            // 
            // mnuView
            // 
            this.mnuView.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuViewReload,
            toolStripMenuItem3,
            this.mnuViewBack,
            this.mnuViewForward,
            this.toolStripMenuItem2,
            this.mnuViewShowSourceCode,
            this.toolStripSeparator2,
            this.mnuViewOptions});
            this.mnuView.Name = "mnuView";
            this.mnuView.Size = new System.Drawing.Size(44, 20);
            this.mnuView.Text = "&View";
            // 
            // mnuViewReload
            // 
            this.mnuViewReload.Image = global::ExceptionExplorer.Properties.Resources.reload;
            this.mnuViewReload.Name = "mnuViewReload";
            this.mnuViewReload.Size = new System.Drawing.Size(173, 22);
            this.mnuViewReload.Text = "&Reload";
            // 
            // mnuViewBack
            // 
            this.mnuViewBack.Image = global::ExceptionExplorer.Properties.Resources.back;
            this.mnuViewBack.Name = "mnuViewBack";
            this.mnuViewBack.Size = new System.Drawing.Size(173, 22);
            this.mnuViewBack.Text = "Nagivate &Back";
            this.mnuViewBack.Click += new System.EventHandler(this.mnuViewBack_Click);
            // 
            // mnuViewForward
            // 
            this.mnuViewForward.Image = global::ExceptionExplorer.Properties.Resources.forward;
            this.mnuViewForward.Name = "mnuViewForward";
            this.mnuViewForward.Size = new System.Drawing.Size(173, 22);
            this.mnuViewForward.Text = "Navigate &Forward";
            this.mnuViewForward.Click += new System.EventHandler(this.mnuViewForward_Click);
            // 
            // toolStripMenuItem2
            // 
            this.toolStripMenuItem2.Name = "toolStripMenuItem2";
            this.toolStripMenuItem2.Size = new System.Drawing.Size(170, 6);
            // 
            // mnuViewShowSourceCode
            // 
            this.mnuViewShowSourceCode.Checked = true;
            this.mnuViewShowSourceCode.CheckOnClick = true;
            this.mnuViewShowSourceCode.CheckState = System.Windows.Forms.CheckState.Checked;
            this.mnuViewShowSourceCode.Image = global::ExceptionExplorer.Properties.Resources.sourcecode;
            this.mnuViewShowSourceCode.Name = "mnuViewShowSourceCode";
            this.mnuViewShowSourceCode.Size = new System.Drawing.Size(173, 22);
            this.mnuViewShowSourceCode.Text = "Show &Source Code";
            // 
            // toolStripSeparator2
            // 
            this.toolStripSeparator2.Name = "toolStripSeparator2";
            this.toolStripSeparator2.Size = new System.Drawing.Size(170, 6);
            // 
            // mnuViewOptions
            // 
            this.mnuViewOptions.Image = global::ExceptionExplorer.Properties.Resources.options;
            this.mnuViewOptions.Name = "mnuViewOptions";
            this.mnuViewOptions.Size = new System.Drawing.Size(173, 22);
            this.mnuViewOptions.Text = "&Options...";
            this.mnuViewOptions.Click += new System.EventHandler(this.mnuViewOptions_Click);
            // 
            // mnuHelp
            // 
            this.mnuHelp.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.mnuHelpWebsite,
            this.mnuHelpUpdate,
            this.mnuHelpLicenceBar,
            this.mnuHelpPurchase,
            this.mnuHelpActivate,
            this.toolStripSeparator3,
            this.mnuHelpAbout});
            this.mnuHelp.Name = "mnuHelp";
            this.mnuHelp.Size = new System.Drawing.Size(44, 20);
            this.mnuHelp.Text = "&Help";
            // 
            // mnuHelpWebsite
            // 
            this.mnuHelpWebsite.Image = global::ExceptionExplorer.Properties.Resources.globe;
            this.mnuHelpWebsite.Name = "mnuHelpWebsite";
            this.mnuHelpWebsite.Size = new System.Drawing.Size(206, 22);
            this.mnuHelpWebsite.Text = "Visit Website";
            this.mnuHelpWebsite.Click += new System.EventHandler(this.mnuHelpWebsite_Click);
            // 
            // mnuHelpUpdate
            // 
            this.mnuHelpUpdate.Name = "mnuHelpUpdate";
            this.mnuHelpUpdate.Size = new System.Drawing.Size(206, 22);
            this.mnuHelpUpdate.Text = "Check for updates";
            this.mnuHelpUpdate.Click += new System.EventHandler(this.mnuHelpUpdate_Click);
            // 
            // mnuHelpLicenceBar
            // 
            this.mnuHelpLicenceBar.Name = "mnuHelpLicenceBar";
            this.mnuHelpLicenceBar.Size = new System.Drawing.Size(203, 6);
            // 
            // mnuHelpPurchase
            // 
            this.mnuHelpPurchase.Name = "mnuHelpPurchase";
            this.mnuHelpPurchase.Size = new System.Drawing.Size(206, 22);
            this.mnuHelpPurchase.Text = "Purchase";
            this.mnuHelpPurchase.Click += new System.EventHandler(this.mnuHelpPurchase_Click);
            // 
            // mnuHelpActivate
            // 
            this.mnuHelpActivate.Name = "mnuHelpActivate";
            this.mnuHelpActivate.Size = new System.Drawing.Size(206, 22);
            this.mnuHelpActivate.Text = "Activate Licence";
            this.mnuHelpActivate.Click += new System.EventHandler(this.mnuHelpActivate_Click);
            // 
            // toolStripSeparator3
            // 
            this.toolStripSeparator3.Name = "toolStripSeparator3";
            this.toolStripSeparator3.Size = new System.Drawing.Size(203, 6);
            // 
            // mnuHelpAbout
            // 
            this.mnuHelpAbout.Name = "mnuHelpAbout";
            this.mnuHelpAbout.Size = new System.Drawing.Size(206, 22);
            this.mnuHelpAbout.Text = "&About Exception Explorer";
            this.mnuHelpAbout.Click += new System.EventHandler(this.mnuHelpAbout_Click);
            // 
            // mnuUpdate
            // 
            this.mnuUpdate.Alignment = System.Windows.Forms.ToolStripItemAlignment.Right;
            this.mnuUpdate.AutoToolTip = true;
            this.mnuUpdate.Name = "mnuUpdate";
            this.mnuUpdate.Size = new System.Drawing.Size(108, 20);
            this.mnuUpdate.Text = "Update Available";
            this.mnuUpdate.ToolTipText = "Click here to download the update";
            this.mnuUpdate.Visible = false;
            this.mnuUpdate.Click += new System.EventHandler(this.mnuUpdate_Click);
            // 
            // exceptionControl
            // 
            this.exceptionControl.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.exceptionControl.Location = new System.Drawing.Point(-1, 52);
            this.exceptionControl.Name = "exceptionControl";
            this.exceptionControl.Size = new System.Drawing.Size(753, 551);
            this.exceptionControl.TabIndex = 7;
            // 
            // toolBar
            // 
            this.toolBar.Location = new System.Drawing.Point(0, 24);
            this.toolBar.Name = "toolBar";
            this.toolBar.Size = new System.Drawing.Size(753, 25);
            this.toolBar.TabIndex = 6;
            this.toolBar.Text = "autoToolStrip1";
            // 
            // ExceptionExplorerForm
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.White;
            this.ClientSize = new System.Drawing.Size(753, 603);
            this.Controls.Add(this.exceptionControl);
            this.Controls.Add(this.toolBar);
            this.Controls.Add(this.menuBar);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.MainMenuStrip = this.menuBar;
            this.MinimumSize = new System.Drawing.Size(300, 300);
            this.Name = "ExceptionExplorerForm";
            this.Text = "Exception Explorer";
            this.Load += new System.EventHandler(this.ExceptionExplorerForm_Load);
            this.Shown += new System.EventHandler(this.ExceptionExplorerForm_Shown);
            this.menuBar.ResumeLayout(false);
            this.menuBar.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.MenuStrip menuBar;
        private System.Windows.Forms.ToolStripMenuItem mnuFile;
        private System.Windows.Forms.ToolStripMenuItem mnuFileOpen;
        private System.Windows.Forms.ToolStripMenuItem mnuFileExit;
        private System.Windows.Forms.ToolStripMenuItem mnuView;
        private System.Windows.Forms.ToolStripMenuItem mnuViewBack;
        private System.Windows.Forms.ToolStripMenuItem mnuViewForward;
        private System.Windows.Forms.ToolStripMenuItem mnuViewReload;
        private System.Windows.Forms.ToolStripMenuItem mnuHelp;
        private System.Windows.Forms.ToolStripMenuItem mnuHelpAbout;
        private AutoToolStrip toolBar;
        private System.Windows.Forms.ToolStripSeparator toolStripMenuItem2;
        private System.Windows.Forms.ToolStripMenuItem mnuViewShowSourceCode;
        private ExceptionControl exceptionControl;
        private System.Windows.Forms.ToolStripMenuItem mnuFileRecent;
        private System.Windows.Forms.ToolStripMenuItem mnuFileRecentNone;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator1;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator2;
        private System.Windows.Forms.ToolStripMenuItem mnuViewOptions;
        private System.Windows.Forms.ToolStripMenuItem mnuHelpWebsite;
        private System.Windows.Forms.ToolStripSeparator mnuHelpLicenceBar;
        private System.Windows.Forms.ToolStripMenuItem mnuHelpPurchase;
        private System.Windows.Forms.ToolStripMenuItem mnuHelpActivate;
        private System.Windows.Forms.ToolStripSeparator toolStripSeparator3;
        private System.Windows.Forms.ToolStripMenuItem mnuHelpUpdate;
        private System.Windows.Forms.ToolStripMenuItem mnuUpdate;
    }
}

