// <autogenerated />
namespace ExceptionExplorer.UI
{
    partial class ExceptionControl
    {
        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ExceptionControl));
            this.images = new System.Windows.Forms.ImageList(this.components);
            this.methodColumn = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.typeColumn = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.sourceSplit = new System.Windows.Forms.SplitContainer();
            this.splitContainerMaster = new System.Windows.Forms.SplitContainer();
            this.sourceViewer = new Decompiler.SourceViewer();
            this.classTree = new ExceptionExplorer.UI.ClassTree();
            this.sourceCodeTitle = new ExceptionExplorer.UI.TitleBar();
            ((System.ComponentModel.ISupportInitialize)(this.sourceSplit)).BeginInit();
            this.sourceSplit.Panel1.SuspendLayout();
            this.sourceSplit.Panel2.SuspendLayout();
            this.sourceSplit.SuspendLayout();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainerMaster)).BeginInit();
            this.splitContainerMaster.Panel1.SuspendLayout();
            this.splitContainerMaster.SuspendLayout();
            this.SuspendLayout();
            // 
            // images
            // 
            this.images.ImageStream = ((System.Windows.Forms.ImageListStreamer)(resources.GetObject("images.ImageStream")));
            this.images.TransparentColor = System.Drawing.Color.Transparent;
            this.images.Images.SetKeyName(0, "assembly");
            this.images.Images.SetKeyName(1, "class");
            this.images.Images.SetKeyName(2, "ctor");
            this.images.Images.SetKeyName(3, "method.override");
            this.images.Images.SetKeyName(4, "method");
            this.images.Images.SetKeyName(5, "property");
            this.images.Images.SetKeyName(6, "exception");
            this.images.Images.SetKeyName(7, "none");
            this.images.Images.SetKeyName(8, "namespace");
            // 
            // methodColumn
            // 
            this.methodColumn.Text = "Method";
            this.methodColumn.Width = 249;
            // 
            // typeColumn
            // 
            this.typeColumn.Text = "Type";
            this.typeColumn.Width = 129;
            // 
            // sourceSplit
            // 
            this.sourceSplit.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sourceSplit.Location = new System.Drawing.Point(0, 0);
            this.sourceSplit.Name = "sourceSplit";
            this.sourceSplit.Orientation = System.Windows.Forms.Orientation.Horizontal;
            // 
            // sourceSplit.Panel1
            // 
            this.sourceSplit.Panel1.Controls.Add(this.splitContainerMaster);
            // 
            // sourceSplit.Panel2
            // 
            this.sourceSplit.Panel2.Controls.Add(this.sourceViewer);
            this.sourceSplit.Panel2.Controls.Add(this.sourceCodeTitle);
            this.sourceSplit.Panel2.Padding = new System.Windows.Forms.Padding(0, 18, 0, 0);
            this.sourceSplit.Size = new System.Drawing.Size(852, 415);
            this.sourceSplit.SplitterDistance = 323;
            this.sourceSplit.TabIndex = 4;
            // 
            // splitContainerMaster
            // 
            this.splitContainerMaster.Dock = System.Windows.Forms.DockStyle.Fill;
            this.splitContainerMaster.Location = new System.Drawing.Point(0, 0);
            this.splitContainerMaster.Margin = new System.Windows.Forms.Padding(0);
            this.splitContainerMaster.Name = "splitContainerMaster";
            // 
            // splitContainerMaster.Panel1
            // 
            this.splitContainerMaster.Panel1.Controls.Add(this.classTree);
            this.splitContainerMaster.Size = new System.Drawing.Size(852, 323);
            this.splitContainerMaster.SplitterDistance = 290;
            this.splitContainerMaster.TabIndex = 5;
            // 
            // sourceViewer
            // 
            this.sourceViewer.DecompileLanguageFeatures = false;
            this.sourceViewer.Dock = System.Windows.Forms.DockStyle.Fill;
            this.sourceViewer.Location = new System.Drawing.Point(0, 18);
            this.sourceViewer.Name = "sourceViewer";
            this.sourceViewer.ShowUsing = false;
            this.sourceViewer.ShowXmlDoc = false;
            this.sourceViewer.Size = new System.Drawing.Size(852, 70);
            this.sourceViewer.TabIndex = 4;
            this.sourceViewer.Text = "sourceViewer1";
            // 
            // classTree
            // 
            this.classTree.Controller = null;
            this.classTree.Dock = System.Windows.Forms.DockStyle.Fill;
            this.classTree.HideSelection = false;
            this.classTree.ImageIndex = 7;
            this.classTree.ImageList = this.images;
            this.classTree.Location = new System.Drawing.Point(0, 0);
            this.classTree.Margin = new System.Windows.Forms.Padding(0);
            this.classTree.Name = "classTree";
            this.classTree.SelectedImageIndex = 0;
            this.classTree.ShowLines = false;
            this.classTree.Size = new System.Drawing.Size(290, 323);
            this.classTree.TabIndex = 2;
            // 
            // sourceCodeTitle
            // 
            this.sourceCodeTitle.Anchor = ((System.Windows.Forms.AnchorStyles)((((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom) 
            | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.sourceCodeTitle.BackColor = System.Drawing.SystemColors.Control;
            this.sourceCodeTitle.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.sourceCodeTitle.Location = new System.Drawing.Point(0, 0);
            this.sourceCodeTitle.Name = "sourceCodeTitle";
            this.sourceCodeTitle.Size = new System.Drawing.Size(852, 18);
            this.sourceCodeTitle.TabIndex = 3;
            this.sourceCodeTitle.Text = "Source code";
            this.sourceCodeTitle.TextAlign = System.Drawing.ContentAlignment.MiddleLeft;
            // 
            // ExceptionControl
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.sourceSplit);
            this.Name = "ExceptionControl";
            this.Size = new System.Drawing.Size(852, 415);
            this.sourceSplit.Panel1.ResumeLayout(false);
            this.sourceSplit.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.sourceSplit)).EndInit();
            this.sourceSplit.ResumeLayout(false);
            this.splitContainerMaster.Panel1.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainerMaster)).EndInit();
            this.splitContainerMaster.ResumeLayout(false);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.SplitContainer splitContainerMaster;
        private ClassTree classTree;
        private System.Windows.Forms.ImageList images;
        private System.Windows.Forms.ColumnHeader typeColumn;
        private System.Windows.Forms.ColumnHeader methodColumn;
        private System.Windows.Forms.SplitContainer sourceSplit;
        private Decompiler.SourceViewer sourceViewer;
        private TitleBar sourceCodeTitle;
    }
}
