/// <autogenerated/>

using System.Reflection;
using System.Runtime.CompilerServices;
using System.Runtime.InteropServices;

[assembly: AssemblyDescription("")]
[assembly: AssemblyConfiguration("")]
[assembly: AssemblyCompany("Steve Grundell")]
[assembly: AssemblyProduct("Exception Explorer")]
[assembly: AssemblyCopyright("Copyright © Steve Grundell 2011-2012")]
[assembly: AssemblyTrademark("")]
[assembly: AssemblyCulture("")]

[assembly: AssemblyVersion("1.0.54.12302")]
[assembly: AssemblyFileVersion("1.0.54.12302")]

[assembly: System.CLSCompliant(true)]
